# # -*- coding: utf-8 -*-
# """PDFChat.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1YYZP1FCm3kfybnv5K_HA_gZoGZmZ6_3N

# ###Installing dependencies
# """

# !pip install -U langchain langchain-core langchain-community faiss-cpu sentence-transformers

# !pip install -q -U google-generativeai

# !pip install pypdf

# !pip install langchain-google-genai

# import google.generativeai as genai

# """###Initializing model"""

# from google.colab import userdata
# api_key = userdata.get('GEMINI_KEY')

# model = genai.GenerativeModel( model_name="gemini-2.5-flash")

# from langchain_google_genai import ChatGoogleGenerativeAI

# model = ChatGoogleGenerativeAI(
#     model="gemini-2.5-flash",
#     temperature=0.5,
#     api_key = api_key
# )

# from langchain_core.documents import Document
# from langchain_community.vectorstores import FAISS
# from langchain_community.embeddings import HuggingFaceEmbeddings

# """###Loading PDF and creating Embedding"""

# from langchain_community.document_loaders import PyPDFLoader
# loader = PyPDFLoader("/content/Jurrasic world.pdf")
# docu = loader.load()
# print("The pdf Loaded successfully!!")

# import re

# def preprocess_text(text):
#     text = re.sub(r'\s+',' ', text)
#     # text = re.sub(r'Page \d+', '', text)
#     text = re.sub(r'[^\w\s\.\,\!\?]', '', text)
#     return text.strip()

# for doc in docu:
#     doc.page_content = preprocess_text(doc.page_content)

# from langchain_text_splitters import RecursiveCharacterTextSplitter

# text_splitter = RecursiveCharacterTextSplitter(
#     chunk_size = 300,
#     chunk_overlap =50
# )
# docs = text_splitter.split_documents(docu)
# print("Chunks ready")

# embedding = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# from langchain_community.vectorstores import FAISS

# db = FAISS.from_documents(docs, embedding)
# print("Vector Database created")

# retriver = db.as_retriever(
#     search_type="similarity",
#     search_kwargs={"k": 5}
# )

# def get_relevant_docs(query):
#     # docs = retriver.get_relevant_documents(query)
#     docs = retriver.invoke(query)
#     return docs

# """### Main bot"""

# def get_chatbot_response_2(user_input):
#     try:
#         system_prompt =  system_prompt = """
#         You are an expert Movie expert.Give short response in 1-2 sentences.
#         """
#         info = get_relevant_docs(user_input)

#         # final_prompt = f"{system_prompt}\nUser: {user_input}\nAssistant:"
#         final_prompt = f"""
#         {system_prompt}

#         Outline Info:
#         {info}

#         User Question:
#         {user_input}

#         SQL Query:
#         """

#         generation_config = {
#         "temperature": 0.6
#           }

#         # response = model.generate_content(final_prompt,generation_config=generation_config)
#         response = model.invoke(final_prompt)

#         if response and hasattr(response, "text"):
#             return response.text
#         else:
#             return "No response generated."

#     except Exception as e:
#         return f"Error: {str(e)}"

# """### Ask PDF"""

# query ="who are the cast in Jurassic world"
# result = get_chatbot_response_2(query)
# print("\nAnswer:", result)

# query ="what was the main theme of the movie"
# result = get_chatbot_response_2(query)
# print("\nAnswer:", result)

